Vagrant.configure("2") do |config|
  #box settings
  config.vm.box = "ubuntu/xenial64"

  #provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 4
  end
  
  #network settings
  config.vm.network "private_network", ip: "192.68.33.10"
  
  #folder settings 
  config.vm.synced_folder "./html/", "/var/www/html", :mount_options => ["dmode=777","fmode=666"]
  
  #provision settings
  config.vm.provision "shell", path: "install.sh"
end
