Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora32"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "file", source: "./ldap", destination: "/vagrant/."
  config.vm.provision "shell", path: "./install.sh"
end
